services:
  postgres_test:
    image: postgres:16
    container_name: postgres_test_db
    restart: always
    environment:
      POSTGRES_USER: anarragan
      POSTGRES_PASSWORD: 1006457424Aa!
      POSTGRES_DB: test_db
    ports:
      - "5433:5432" # el puerto 5433 es local, 5432 dentro del contenedor
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
volumes:
  postgres_test_data: